### ISSUE TITLE
Problem with web_promo

### ISSUE THREAD

**Issue by absolutezeroo** [higoka/habbo-downloader#10] opened 2020-04-21 16:28 UTC
The command promo download only web_promo_small not web_promo
And i can't run targetedoffers command

// Targetedoffers
https://i.imgur.com/gmslZno.png

// Promo
https://i.imgur.com/JYdwaav.png
https://i.imgur.com/JAKoNgA.png

I use windows 10

**Comment by higoka** [comment] 2020-04-21 19:12
hey

so the web_promo folder is empty because in the external_variables only small images exist. so there are no large web_promo images only small ones. i should remove the web_promo and only keep web_promo_small instead.

for the targetedoffers im not sure maybe i broke something with the update i made yesterday. can you please try again with an older version like 1.11.2 and see if it still doesnt work?

**Comment by absolutezeroo** [comment] 2020-04-21 19:35
Always the same concern for targetedoffers

**Comment by higoka** [comment] 2020-04-21 19:49
okay weird. i need to test it myself and fix it if its broken but im currently very busy with work so please be patient. 

and thanks for the issue report!

**Comment by higoka** [comment] 2020-04-22 16:55
Okay i found the problem with the `targetedoffers` command. Well it isn't really a problem. You are using the Habbo.fr external_variables and there are not targetedoffers defined. So the command is working as intended but it just couldn't find anything. You can however download the targedetoffers from the Habbo.com domain. Just change the domain to `com` in your config.

Im closing this issue now. Feel free to create a new one if you have questions or anything. Thanks again for your issue report!

**Closed by higoka** 2020-04-22 16:55 UTC
